//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFBaseDemo.Host.DeploymentTests.ServiceReferences {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferences.IDummyService")]
    public interface IDummyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDummyService/SayHello", ReplyAction="http://tempuri.org/IDummyService/SayHelloResponse")]
        string SayHello(string toWho);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDummyServiceChannel : WCFBaseDemo.Host.DeploymentTests.ServiceReferences.IDummyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DummyServiceClient : System.ServiceModel.ClientBase<WCFBaseDemo.Host.DeploymentTests.ServiceReferences.IDummyService>, WCFBaseDemo.Host.DeploymentTests.ServiceReferences.IDummyService {
        
        public DummyServiceClient() {
        }
        
        public DummyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DummyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DummyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DummyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SayHello(string toWho) {
            return base.Channel.SayHello(toWho);
        }
    }
}
